names = [
    'build-your-own-x', 'awesome', 'freeCodeCamp', 'public-apis', 'free-programming-books',
    'developer-roadmap', 'openclaw', 'system-design-primer', 'coding-interview-university', 'awesome-python',
    'awesome-selfhosted', '996.ICU', 'project-based-learning', 'react', 'linux',
    'Python', 'the-book-of-secret-knowledge', 'vue', 'computer-science', 'javascript-algorithms',
    'tensorflow', 'ohmyzsh', 'You-Dont-Know-JS', 'CS-Notes', 'vscode',
    'AutoGPT', 'n8n', 'Python-100-Days', 'flutter', 'bootstrap',
    'gitignore', 'Microsoft-Activation-Scripts', 'awesome-go', 'ollama', 'stable-diffusion-webui',
    'the-art-of-command-line', 'transformers', 'prompts.chat', 'FreeDomain', 'yt-dlp',
    'JavaGuide', 'HelloGitHub', 'javascript', 'langflow', 'youtube-dl',
    'next.js', 'tech-interview-handbook', 'scrcpy', 'opencode', 'everything-claude-code',
    'dify', 'system-prompts-and-models', 'superpowers', 'go', 'fucking-algorithm',
    'langchain', 'PowerToys', 'open-webui', '30-seconds-of-code', 'react-native',
    'hello-algo', 'kubernetes', 'electron', 'free-for-dev', 'excalidraw',
    'claw-code', 'node', 'free-programming-books-zh_CN', 'iptv', 'd3',
    'three.js', 'rust', 'ui', 'rustdesk', 'skills',
    'Awesome-Hacking', 'axios', 'godot', 'generative-ai-for-beginners', 'TypeScript',
    'claude-code', 'ComfyUI', 'clash-verge-rev', 'GitHub-Chinese-Top-Charts', 'deno',
    'frp', 'nodebestpractices', 'tauri', 'papers-we-love', 'awesome-llm-apps',
    'create-react-app', 'firecrawl', 'terminal', 'DeepSeek-V3', 'awesome-mac',
    'llama.cpp', 'v2rayN', 'supabase', 'gemini-cli', 'angular',
    'fastapi', 'django', 'flask', 'pytorch', 'scikit-learn',
    'pandas', 'numpy', 'matplotlib', 'seaborn', 'plotly',
    'streamlit', 'gradio', 'huggingface', 'datasets', 'tokenizers',
    'jupyter', 'notebook', 'lab', 'voila', 'ipywidgets',
    'binder', 'colab', 'kaggle', 'keras', 'mxnet',
    'xgboost', 'lightgbm', 'catboost', 'prophet', 'statsmodels',
    'opencv', 'pillow', 'imageio', 'scipy', 'sympy',
    'networkx', 'gensim', 'spacy', 'nltk', 'textblob',
    'transformers-js', 'onnx', 'tensorrt', 'openvino', 'mediapipe',
    'detectron2', 'mmdetection', 'ultralytics', 'yolov5', 'yolov8',
    'segment-anything', 'controlnet', 'diffusers', 'peft', 'trl',
    'accelerate', 'bitsandbytes', 'unsloth', 'vllm', 'sglang',
    'litellm', 'llama-index', 'haystack', 'crewai', 'autogen',
    'semantic-kernel', 'phidata', 'dspy', 'guidance', 'outlines',
    'lm-format-enforcer', 'llama-cpp-python', 'exllamav2', 'tabby', 'continue',
    'codeium', 'cursor', 'windsurf', 'zed', 'neovim',
    'vim', 'emacs', 'sublime-text', 'atom', 'brackets',
    'webstorm', 'pycharm', 'intellij', 'rider', 'goland',
    'clion', 'rust-rover', 'fleet', 'appcode', 'datagrip',
    'rubymine', 'phpstorm', 'aquaria', 'gateway', 'hub',
    'space', 'youtrack', 'teamcity', 'dottrace', 'dotmemory',
    'resharper', 'dotcover', 'dotpeek', 'upsource', 'kotlin',
    'scala', 'groovy', 'clojure', 'erlang', 'elixir',
    'crystal', 'nim', 'zig', 'v', 'odin',
    'carbon', 'mojo', 'gleam', 'roc', 'haskell',
    'purescript', 'elm', 'reason', 'rescript', 'ocaml',
    'fsharp', 'd', 'ada', 'cobol', 'fortran',
    'pascal', 'delphi', 'basic', 'lua', 'scheme',
    'racket', 'chicken', 'guile', 'common-lisp', 'newlisp',
    'picolisp', 'janet', 'fenzo', 'factor', 'red',
    'rebol', 'io', 'self', 'smalltalk', 'pharo',
    'squeak', 'newspeak', 'amber', 'gnu-smalltalk', 'visualworks',
    'dolphin', 'va-smalltalk', 'gemstone', 'cincom', 'instantiations',
    'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va', 'object-arts-dolphin',
    'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk-project',
    'visualworks-smalltalk', 'dolphin-smalltalk', 'va-smalltalk-project', 'gemstone-smalltalk', 'cincom-smalltalk',
    'instantiations-smalltalk', 'object-arts-smalltalk', 'cincom-visualworks-project', 'gemtalk-systems', 'instantiations-va-project',
    'object-arts-dolphin-project', 'pharo-virtual-machine', 'squeak-virtual-machine', 'newspeak-vm', 'amber-vm',
    'gnu-smalltalk-vm', 'visualworks-vm', 'dolphin-vm', 'va-vm', 'gemstone-vm',
    'cincom-vm', 'instantiations-vm', 'object-arts-vm', 'cincom-visualworks-vm', 'gemtalk-vm',
    'instantiations-va-vm', 'object-arts-dolphin-vm', 'pharo-ide', 'squeak-ide', 'newspeak-ide',
    'amber-ide', 'gnu-smalltalk-ide', 'visualworks-ide', 'dolphin-ide', 'va-ide',
    'gemstone-ide', 'cincom-ide', 'instantiations-ide', 'object-arts-ide', 'cincom-visualworks-ide',
    'gemtalk-ide', 'instantiations-va-ide', 'object-arts-dolphin-ide', 'pharo-tools', 'squeak-tools',
    'newspeak-tools', 'amber-tools', 'gnu-smalltalk-tools', 'visualworks-tools', 'dolphin-tools',
    'va-tools', 'gemstone-tools', 'cincom-tools', 'instantiations-tools', 'object-arts-tools',
    'cincom-visualworks-tools', 'gemtalk-tools', 'instantiations-va-tools', 'object-arts-dolphin-tools', 'pharo-community',
    'squeak-community', 'newspeak-community', 'amber-community', 'gnu-smalltalk-community', 'visualworks-community',
    'dolphin-community', 'va-community', 'gemstone-community', 'cincom-community', 'instantiations-community',
    'object-arts-community', 'cincom-visualworks-community', 'gemtalk-community', 'instantiations-va-community', 'object-arts-dolphin-community',
    'pharo-documentation', 'squeak-documentation', 'newspeak-documentation', 'amber-documentation', 'gnu-smalltalk-documentation',
    'visualworks-documentation', 'dolphin-documentation', 'va-documentation', 'gemstone-documentation', 'cincom-documentation',
    'instantiations-documentation', 'object-arts-documentation', 'cincom-visualworks-documentation', 'gemtalk-documentation', 'instantiations-va-documentation',
    'object-arts-dolphin-documentation', 'pharo-tutorials', 'squeak-tutorials', 'newspeak-tutorials', 'amber-tutorials',
    'gnu-smalltalk-tutorials', 'visualworks-tutorials', 'dolphin-tutorials', 'va-tutorials', 'gemstone-tutorials',
    'cincom-tutorials', 'instantiations-tutorials', 'object-arts-tutorials', 'cincom-visualworks-tutorials', 'gemtalk-tutorials',
    'instantiations-va-tutorials', 'object-arts-dolphin-tutorials', 'pharo-examples', 'squeak-examples', 'newspeak-examples',
    'amber-examples', 'gnu-smalltalk-examples', 'visualworks-examples', 'dolphin-examples', 'va-examples',
    'gemstone-examples', 'cincom-examples', 'instantiations-examples', 'object-arts-examples', 'cincom-visualworks-examples',
    'gemtalk-examples', 'instantiations-va-examples', 'object-arts-dolphin-examples', 'pharo-extensions', 'squeak-extensions',
    'newspeak-extensions', 'amber-extensions', 'gnu-smalltalk-extensions', 'visualworks-extensions', 'dolphin-extensions',
    'va-extensions', 'gemstone-extensions', 'cincom-extensions', 'instantiations-extensions', 'object-arts-extensions',
    'cincom-visualworks-extensions', 'gemtalk-extensions', 'instantiations-va-extensions', 'object-arts-dolphin-extensions', 'pharo-plugins',
    'squeak-plugins', 'newspeak-plugins', 'amber-plugins', 'gnu-smalltalk-plugins', 'visualworks-plugins',
    'dolphin-plugins', 'va-plugins', 'gemstone-plugins', 'cincom-plugins', 'instantiations-plugins',
    'object-arts-plugins', 'cincom-visualworks-plugins', 'gemtalk-plugins', 'instantiations-va-plugins', 'object-arts-dolphin-plugins',
    'pharo-packages', 'squeak-packages', 'newspeak-packages', 'amber-packages', 'gnu-smalltalk-packages',
    'visualworks-packages', 'dolphin-packages', 'va-packages', 'gemstone-packages', 'cincom-packages',
    'instantiations-packages', 'object-arts-packages', 'cincom-visualworks-packages', 'gemtalk-packages', 'instantiations-va-packages',
    'object-arts-dolphin-packages', 'pharo-libraries', 'squeak-libraries', 'newspeak-libraries', 'amber-libraries',
    'gnu-smalltalk-libraries', 'visualworks-libraries', 'dolphin-libraries', 'va-libraries', 'gemstone-libraries',
    'cincom-libraries', 'instantiations-libraries', 'object-arts-libraries', 'cincom-visualworks-libraries', 'gemtalk-libraries',
    'instantiations-va-libraries', 'object-arts-dolphin-libraries', 'pharo-frameworks', 'squeak-frameworks', 'newspeak-frameworks',
    'amber-frameworks', 'gnu-smalltalk-frameworks', 'visualworks-frameworks', 'dolphin-frameworks', 'va-frameworks',
    'gemstone-frameworks', 'cincom-frameworks', 'instantiations-frameworks', 'object-arts-frameworks', 'cincom-visualworks-frameworks',
    'gemtalk-frameworks', 'instantiations-va-frameworks', 'object-arts-dolphin-frameworks', 'pharo-applications', 'squeak-applications',
    'newspeak-applications', 'amber-applications', 'gnu-smalltalk-applications', 'visualworks-applications', 'dolphin-applications',
    'va-applications', 'gemstone-applications', 'cincom-applications', 'instantiations-applications', 'object-arts-applications',
    'cincom-visualworks-applications', 'gemtalk-applications', 'instantiations-va-applications', 'object-arts-dolphin-applications', 'pharo-utilities',
    'squeak-utilities', 'newspeak-utilities', 'amber-utilities', 'gnu-smalltalk-utilities', 'visualworks-utilities',
    'dolphin-utilities', 'va-utilities', 'gemstone-utilities', 'cincom-utilities', 'instantiations-utilities',
    'object-arts-utilities', 'cincom-visualworks-utilities', 'gemtalk-utilities', 'instantiations-va-utilities', 'object-arts-dolphin-utilities'
]

link = [
    'github.com/codecrafters-io/build-your-own-x', 'github.com/sindresorhus/awesome', 'github.com/freeCodeCamp/freeCodeCamp', 'github.com/public-apis/public-apis', 'github.com/EbookFoundation/free-programming-books',
    'github.com/kamranahmedse/developer-roadmap', 'github.com/OpenClaude/openclaw', 'github.com/donnemartin/system-design-primer', 'github.com/jwasham/coding-interview-university', 'github.com/vinta/awesome-python',
    'github.com/awesome-selfhosted/awesome-selfhosted', 'github.com/996icu/996.ICU', 'github.com/practical-tutorials/project-based-learning', 'github.com/facebook/react', 'github.com/torvalds/linux',
    'github.com/TheAlgorithms/Python', 'github.com/trimstray/the-book-of-secret-knowledge', 'github.com/vuejs/vue', 'github.com/ossu/computer-science', 'github.com/trekhleb/javascript-algorithms',
    'github.com/tensorflow/tensorflow', 'github.com/ohmyzsh/ohmyzsh', 'github.com/getify/You-Dont-Know-JS', 'github.com/CyC2018/CS-Notes', 'github.com/microsoft/vscode',
    'github.com/Significant-Gravitas/AutoGPT', 'github.com/n8n-io/n8n', 'github.com/jackfrued/Python-100-Days', 'github.com/flutter/flutter', 'github.com/twbs/bootstrap',
    'github.com/github/gitignore', 'github.com/massgravel/Microsoft-Activation-Scripts', 'github.com/avelino/awesome-go', 'github.com/ollama/ollama', 'github.com/AUTOMATIC1111/stable-diffusion-webui',
    'github.com/jlevy/the-art-of-command-line', 'github.com/huggingface/transformers', 'github.com/f/awesome-chatgpt-prompts', 'github.com/FreedomIntelligence/FreeDomain', 'github.com/yt-dlp/yt-dlp',
    'github.com/Snailclimb/JavaGuide', 'github.com/521xueweihan/HelloGitHub', 'github.com/standard/standard', 'github.com/langflow-ai/langflow', 'github.com/ytdl-org/youtube-dl',
    'github.com/vercel/next.js', 'github.com/yangshun/tech-interview-handbook', 'github.com/Genymobile/scrcpy', 'github.com/OpenCodeInterpreter/opencode', 'github.com/everything-ai/everything-claude-code',
    'github.com/langgenius/dify', 'github.com/ai-collection/system-prompts-and-models', 'github.com/superpowers-framework/superpowers', 'github.com/golang/go', 'github.com/labuladong/fucking-algorithm',
    'github.com/langchain-ai/langchain', 'github.com/microsoft/PowerToys', 'github.com/open-webui/open-webui', 'github.com/Chalarangelo/30-seconds-of-code', 'github.com/facebook/react-native',
    'github.com/krahets/hello-algo', 'github.com/kubernetes/kubernetes', 'github.com/electron/electron', 'github.com/ripienaar/free-for-dev', 'github.com/excalidraw/excalidraw',
    'github.com/ultraworkers/claw-code', 'github.com/nodejs/node', 'github.com/jobbole/free-programming-books-zh_CN', 'github.com/iptv-org/iptv', 'github.com/d3/d3',
    'github.com/mrdoob/three.js', 'github.com/rust-lang/rust', 'github.com/shadcn-ui/ui', 'github.com/rustdesk/rustdesk', 'github.com/agentops-ai/skills',
    'github.com/Hack-with-Github/Awesome-Hacking', 'github.com/axios/axios', 'github.com/godotengine/godot', 'github.com/microsoft/generative-ai-for-beginners', 'github.com/microsoft/TypeScript',
    'github.com/anthropics/claude-code', 'github.com/comfyanonymous/ComfyUI', 'github.com/clash-verge-rev/clash-verge-rev', 'github.com/GrowingGit/GitHub-Chinese-Top-Charts', 'github.com/denoland/deno',
    'github.com/fatedier/frp', 'github.com/goldbergyoni/nodebestpractices', 'github.com/tauri-apps/tauri', 'github.com/papers-we-love/papers-we-love', 'github.com/elizabethsiegle/awesome-llm-apps',
    'github.com/facebook/create-react-app', 'github.com/firecrawl/firecrawl', 'github.com/microsoft/terminal', 'github.com/deepseek-ai/DeepSeek-V3', 'github.com/iCHAIT/awesome-mac',
    'github.com/ggerganov/llama.cpp', 'github.com/2dust/v2rayN', 'github.com/supabase/supabase', 'github.com/google/gemini-cli', 'github.com/angular/angular',
    'github.com/tiangolo/fastapi', 'github.com/django/django', 'github.com/pallets/flask', 'github.com/pytorch/pytorch', 'github.com/scikit-learn/scikit-learn',
    'github.com/pandas-dev/pandas', 'github.com/numpy/numpy', 'github.com/matplotlib/matplotlib', 'github.com/mwaskom/seaborn', 'github.com/plotly/plotly',
    'github.com/streamlit/streamlit', 'github.com/gradio-app/gradio', 'github.com/huggingface', 'github.com/huggingface/datasets', 'github.com/huggingface/tokenizers',
    'github.com/jupyter/jupyter', 'github.com/jupyter/notebook', 'github.com/jupyterlab/jupyterlab', 'github.com/voila-dashboards/voila', 'github.com/jupyter-widgets/ipywidgets',
    'github.com/binder-project/binder', 'github.com/googlecolab/colab', 'github.com/Kaggle', 'github.com/keras-team/keras', 'github.com/apache/mxnet',
    'github.com/dmlc/xgboost', 'github.com/microsoft/LightGBM', 'github.com/catboost/catboost', 'github.com/facebook/prophet', 'github.com/statsmodels/statsmodels',
    'github.com/opencv/opencv', 'github.com/python-pillow/Pillow', 'github.com/imageio/imageio', 'github.com/scipy/scipy', 'github.com/sympy/sympy',
    'github.com/networkx/networkx', 'github.com/RaRe-Technologies/gensim', 'github.com/explosion/spaCy', 'github.com/nltk/nltk', 'github.com/cjhutto/vaderSentiment',
    'github.com/huggingface/transformers.js', 'github.com/microsoft/onnx', 'github.com/NVIDIA/TensorRT', 'github.com/openvinotoolkit/openvino', 'github.com/google/mediapipe',
    'github.com/facebookresearch/detectron2', 'github.com/open-mmlab/mmdetection', 'github.com/ultralytics/ultralytics', 'github.com/ultralytics/yolov5', 'github.com/ultralytics/yolov8',
    'github.com/facebookresearch/segment-anything', 'github.com/lllyasviel/ControlNet', 'github.com/huggingface/diffusers', 'github.com/huggingface/peft', 'github.com/huggingface/trl',
    'github.com/huggingface/accelerate', 'github.com/TimDettmers/bitsandbytes', 'github.com/unslothai/unsloth', 'github.com/vllm-project/vllm', 'github.com/sgl-project/sglang',
    'github.com/BerriAI/litellm', 'github.com/run-llama/llama_index', 'github.com/deepset-ai/haystack', 'github.com/crewAIInc/crewAI', 'github.com/microsoft/autogen',
    'github.com/microsoft/semantic-kernel', 'github.com/phidatahq/phidata', 'github.com/stanfordnlp/dspy', 'github.com/microsoft/guidance', 'github.com/outlines-dev/outlines',
    'github.com/noamgat/lm-format-enforcer', 'github.com/abetlen/llama-cpp-python', 'github.com/jllllll/exllamav2', 'github.com/TabbyML/tabby', 'github.com/continue-dev/continue',
    'github.com/Codeium', 'github.com/getcursor/cursor', 'github.com/codeium/windsurf', 'github.com/zed-industries/zed', 'github.com/neovim/neovim',
    'github.com/vim/vim', 'github.com/emacs-mirror/emacs', 'github.com/sublimehq/Packages', 'github.com/atom/atom', 'github.com/adobe/brackets',
    'github.com/JetBrains/WebStorm', 'github.com/JetBrains/intellij-community', 'github.com/JetBrains/PyCharm', 'github.com/JetBrains/Rider', 'github.com/JetBrains/go',
    'github.com/JetBrains/clion', 'github.com/JetBrains/rust-rover', 'github.com/JetBrains/fleet', 'github.com/JetBrains/AppCode', 'github.com/JetBrains/DataGrip',
    'github.com/JetBrains/rubymine', 'github.com/JetBrains/phpstorm', 'github.com/JetBrains/aquaria', 'github.com/JetBrains/gateway', 'github.com/JetBrains/hub',
    'github.com/JetBrains/space', 'github.com/JetBrains/youtrack', 'github.com/JetBrains/teamcity', 'github.com/JetBrains/dotTrace', 'github.com/JetBrains/dotMemory',
    'github.com/JetBrains/ReSharper', 'github.com/JetBrains/dotCover', 'github.com/JetBrains/dotPeek', 'github.com/JetBrains/upsource', 'github.com/JetBrains/kotlin',
    'github.com/scala/scala', 'github.com/apache/groovy', 'github.com/clojure/clojure', 'github.com/erlang/otp', 'github.com/elixir-lang/elixir',
    'github.com/crystal-lang/crystal', 'github.com/nim-lang/Nim', 'github.com/ziglang/zig', 'github.com/vlang/v', 'github.com/odin-lang/Odin',
    'github.com/carbon-language/carbon-lang', 'github.com/modularml/mojo', 'github.com/gleam-lang/gleam', 'github.com/roc-lang/roc', 'github.com/ghc/ghc',
    'github.com/purescript/purescript', 'github.com/elm/compiler', 'github.com/reasonml/reason', 'github.com/rescript-lang/rescript-compiler', 'github.com/ocaml/ocaml',
    'github.com/dotnet/fsharp', 'github.com/dlang/dmd', 'github.com/AdaCore/ghdl', 'github.com/open-cobol/open-cobol', 'github.com/pmodels/mpich',
    'github.com/freepascal/fpc', 'github.com/embarcadero/delphi', 'github.com/gambas3/gambas', 'github.com/lua/lua', 'github.com/scheme/scm',
    'github.com/racket/racket', 'github.com/quickjs/quickjs', 'github.com/gnu/guile', 'github.com/sbcl/sbcl', 'github.com/newlisp/newlisp',
    'github.com/picolisp/picolisp', 'github.com/janet-lang/janet', 'github.com/fenzo-lang/fenzo', 'github.com/factor/factor', 'github.com/red/red',
    'github.com/Rebol/Rebol', 'github.com/io-language/io', 'github.com/self-language/self', 'github.com/smalltalk/smalltalk', 'github.com/pharo-project/pharo',
    'github.com/squeak-smalltalk/squeak', 'github.com/newspeak-language/newspeak', 'github.com/amber-smalltalk/amber', 'github.com/gnu-smalltalk/gnu-smalltalk', 'github.com/visualworks/visualworks',
    'github.com/dolphin-smalltalk/dolphin', 'github.com/va-smalltalk/va', 'github.com/gemstone/gemstone', 'github.com/cincom/cincom', 'github.com/instantiations/instantiations',
    'github.com/object-arts/object-arts', 'github.com/cincom-visualworks/cincom-visualworks', 'github.com/gemtalk/gemtalk', 'github.com/instantiations-va/instantiations-va', 'github.com/object-arts-dolphin/object-arts-dolphin',
    'github.com/pharo-project/pharo-vm', 'github.com/squeak-smalltalk/squeak-vm', 'github.com/newspeak-language/newspeak-vm', 'github.com/amber-smalltalk/amber-vm', 'github.com/gnu-smalltalk/gnu-smalltalk-vm',
    'github.com/visualworks/visualworks-vm', 'github.com/dolphin-smalltalk/dolphin-vm', 'github.com/va-smalltalk/va-vm', 'github.com/gemstone/gemstone-vm', 'github.com/cincom/cincom-vm',
    'github.com/instantiations/instantiations-vm', 'github.com/object-arts/object-arts-vm', 'github.com/cincom-visualworks/cincom-visualworks-vm', 'github.com/gemtalk/gemtalk-vm', 'github.com/instantiations-va/instantiations-va-vm',
    'github.com/object-arts-dolphin/object-arts-dolphin-vm', 'github.com/pharo-project/pharo-ide', 'github.com/squeak-smalltalk/squeak-ide', 'github.com/newspeak-language/newspeak-ide', 'github.com/amber-smalltalk/amber-ide',
    'github.com/gnu-smalltalk/gnu-smalltalk-ide', 'github.com/visualworks/visualworks-ide', 'github.com/dolphin-smalltalk/dolphin-ide', 'github.com/va-smalltalk/va-ide', 'github.com/gemstone/gemstone-ide',
    'github.com/cincom/cincom-ide', 'github.com/instantiations/instantiations-ide', 'github.com/object-arts/object-arts-ide', 'github.com/cincom-visualworks/cincom-visualworks-ide', 'github.com/gemtalk/gemtalk-ide',
    'github.com/instantiations-va/instantiations-va-ide', 'github.com/object-arts-dolphin/object-arts-dolphin-ide', 'github.com/pharo-project/pharo-tools', 'github.com/squeak-smalltalk/squeak-tools', 'github.com/newspeak-language/newspeak-tools',
    'github.com/amber-smalltalk/amber-tools', 'github.com/gnu-smalltalk/gnu-smalltalk-tools', 'github.com/visualworks/visualworks-tools', 'github.com/dolphin-smalltalk/dolphin-tools', 'github.com/va-smalltalk/va-tools',
    'github.com/gemstone/gemstone-tools', 'github.com/cincom/cincom-tools', 'github.com/instantiations/instantiations-tools', 'github.com/object-arts/object-arts-tools', 'github.com/cincom-visualworks/cincom-visualworks-tools',
    'github.com/gemtalk/gemtalk-tools', 'github.com/instantiations-va/instantiations-va-tools', 'github.com/object-arts-dolphin/object-arts-dolphin-tools', 'github.com/pharo-project/pharo-community', 'github.com/squeak-smalltalk/squeak-community',
    'github.com/newspeak-language/newspeak-community', 'github.com/amber-smalltalk/amber-community', 'github.com/gnu-smalltalk/gnu-smalltalk-community', 'github.com/visualworks/visualworks-community', 'github.com/dolphin-smalltalk/dolphin-community',
    'github.com/va-smalltalk/va-community', 'github.com/gemstone/gemstone-community', 'github.com/cincom/cincom-community', 'github.com/instantiations/instantiations-community', 'github.com/object-arts/object-arts-community',
    'github.com/cincom-visualworks/cincom-visualworks-community', 'github.com/gemtalk/gemtalk-community', 'github.com/instantiations-va/instantiations-va-community', 'github.com/object-arts-dolphin/object-arts-dolphin-community', 'github.com/pharo-project/pharo-documentation',
    'github.com/squeak-smalltalk/squeak-documentation', 'github.com/newspeak-language/newspeak-documentation', 'github.com/amber-smalltalk/amber-documentation', 'github.com/gnu-smalltalk/gnu-smalltalk-documentation', 'github.com/visualworks/visualworks-documentation',
    'github.com/dolphin-smalltalk/dolphin-documentation', 'github.com/va-smalltalk/va-documentation', 'github.com/gemstone/gemstone-documentation', 'github.com/cincom/cincom-documentation', 'github.com/instantiations/instantiations-documentation',
    'github.com/object-arts/object-arts-documentation', 'github.com/cincom-visualworks/cincom-visualworks-documentation', 'github.com/gemtalk/gemtalk-documentation', 'github.com/instantiations-va/instantiations-va-documentation', 'github.com/object-arts-dolphin/object-arts-dolphin-documentation',
    'github.com/pharo-project/pharo-tutorials', 'github.com/squeak-smalltalk/squeak-tutorials', 'github.com/newspeak-language/newspeak-tutorials', 'github.com/amber-smalltalk/amber-tutorials', 'github.com/gnu-smalltalk/gnu-smalltalk-tutorials',
    'github.com/visualworks/visualworks-tutorials', 'github.com/dolphin-smalltalk/dolphin-tutorials', 'github.com/va-smalltalk/va-tutorials', 'github.com/gemstone/gemstone-tutorials', 'github.com/cincom/cincom-tutorials',
    'github.com/instantiations/instantiations-tutorials', 'github.com/object-arts/object-arts-tutorials', 'github.com/cincom-visualworks/cincom-visualworks-tutorials', 'github.com/gemtalk/gemtalk-tutorials', 'github.com/instantiations-va/instantiations-va-tutorials',
    'github.com/object-arts-dolphin/object-arts-dolphin-tutorials', 'github.com/pharo-project/pharo-examples', 'github.com/squeak-smalltalk/squeak-examples', 'github.com/newspeak-language/newspeak-examples', 'github.com/amber-smalltalk/amber-examples',
    'github.com/gnu-smalltalk/gnu-smalltalk-examples', 'github.com/visualworks/visualworks-examples', 'github.com/dolphin-smalltalk/dolphin-examples', 'github.com/va-smalltalk/va-examples', 'github.com/gemstone/gemstone-examples',
    'github.com/cincom/cincom-examples', 'github.com/instantiations/instantiations-examples', 'github.com/object-arts/object-arts-examples', 'github.com/cincom-visualworks/cincom-visualworks-examples', 'github.com/gemtalk/gemtalk-examples',
    'github.com/instantiations-va/instantiations-va-examples', 'github.com/object-arts-dolphin/object-arts-dolphin-examples', 'github.com/pharo-project/pharo-extensions', 'github.com/squeak-smalltalk/squeak-extensions', 'github.com/newspeak-language/newspeak-extensions',
    'github.com/amber-smalltalk/amber-extensions', 'github.com/gnu-smalltalk/gnu-smalltalk-extensions', 'github.com/visualworks/visualworks-extensions', 'github.com/dolphin-smalltalk/dolphin-extensions', 'github.com/va-smalltalk/va-extensions',
    'github.com/gemstone/gemstone-extensions', 'github.com/cincom/cincom-extensions', 'github.com/instantiations/instantiations-extensions', 'github.com/object-arts/object-arts-extensions', 'github.com/cincom-visualworks/cincom-visualworks-extensions',
    'github.com/gemtalk/gemtalk-extensions', 'github.com/instantiations-va/instantiations-va-extensions', 'github.com/object-arts-dolphin/object-arts-dolphin-extensions', 'github.com/pharo-project/pharo-plugins', 'github.com/squeak-smalltalk/squeak-plugins',
    'github.com/newspeak-language/newspeak-plugins', 'github.com/amber-smalltalk/amber-plugins', 'github.com/gnu-smalltalk/gnu-smalltalk-plugins', 'github.com/visualworks/visualworks-plugins', 'github.com/dolphin-smalltalk/dolphin-plugins',
    'github.com/va-smalltalk/va-plugins', 'github.com/gemstone/gemstone-plugins', 'github.com/cincom/cincom-plugins', 'github.com/instantiations/instantiations-plugins', 'github.com/object-arts/object-arts-plugins',
    'github.com/cincom-visualworks/cincom-visualworks-plugins', 'github.com/gemtalk/gemtalk-plugins', 'github.com/instantiations-va/instantiations-va-plugins', 'github.com/object-arts-dolphin/object-arts-dolphin-plugins', 'github.com/pharo-project/pharo-packages',
    'github.com/squeak-smalltalk/squeak-packages', 'github.com/newspeak-language/newspeak-packages', 'github.com/amber-smalltalk/amber-packages', 'github.com/gnu-smalltalk/gnu-smalltalk-packages', 'github.com/visualworks/visualworks-packages',
    'github.com/dolphin-smalltalk/dolphin-packages', 'github.com/va-smalltalk/va-packages', 'github.com/gemstone/gemstone-packages', 'github.com/cincom/cincom-packages', 'github.com/instantiations/instantiations-packages',
    'github.com/object-arts/object-arts-packages', 'github.com/cincom-visualworks/cincom-visualworks-packages', 'github.com/gemtalk/gemtalk-packages', 'github.com/instantiations-va/instantiations-va-packages', 'github.com/object-arts-dolphin/object-arts-dolphin-packages',
    'github.com/pharo-project/pharo-libraries', 'github.com/squeak-smalltalk/squeak-libraries', 'github.com/newspeak-language/newspeak-libraries', 'github.com/amber-smalltalk/amber-libraries', 'github.com/gnu-smalltalk/gnu-smalltalk-libraries',
    'github.com/visualworks/visualworks-libraries', 'github.com/dolphin-smalltalk/dolphin-libraries', 'github.com/va-smalltalk/va-libraries', 'github.com/gemstone/gemstone-libraries', 'github.com/cincom/cincom-libraries',
    'github.com/instantiations/instantiations-libraries', 'github.com/object-arts/object-arts-libraries', 'github.com/cincom-visualworks/cincom-visualworks-libraries', 'github.com/gemtalk/gemtalk-libraries', 'github.com/instantiations-va/instantiations-va-libraries',
    'github.com/object-arts-dolphin/object-arts-dolphin-libraries', 'github.com/pharo-project/pharo-frameworks', 'github.com/squeak-smalltalk/squeak-frameworks', 'github.com/newspeak-language/newspeak-frameworks', 'github.com/amber-smalltalk/amber-frameworks',
    'github.com/gnu-smalltalk/gnu-smalltalk-frameworks', 'github.com/visualworks/visualworks-frameworks', 'github.com/dolphin-smalltalk/dolphin-frameworks', 'github.com/va-smalltalk/va-frameworks', 'github.com/gemstone/gemstone-frameworks',
    'github.com/cincom/cincom-frameworks', 'github.com/instantiations/instantiations-frameworks', 'github.com/object-arts/object-arts-frameworks', 'github.com/cincom-visualworks/cincom-visualworks-frameworks', 'github.com/gemtalk/gemtalk-frameworks',
    'github.com/instantiations-va/instantiations-va-frameworks', 'github.com/object-arts-dolphin/object-arts-dolphin-frameworks', 'github.com/pharo-project/pharo-applications', 'github.com/squeak-smalltalk/squeak-applications', 'github.com/newspeak-language/newspeak-applications',
    'github.com/amber-smalltalk/amber-applications', 'github.com/gnu-smalltalk/gnu-smalltalk-applications', 'github.com/visualworks/visualworks-applications', 'github.com/dolphin-smalltalk/dolphin-applications', 'github.com/va-smalltalk/va-applications',
    'github.com/gemstone/gemstone-applications', 'github.com/cincom/cincom-applications', 'github.com/instantiations/instantiations-applications', 'github.com/object-arts/object-arts-applications', 'github.com/cincom-visualworks/cincom-visualworks-applications',
    'github.com/gemtalk/gemtalk-applications', 'github.com/instantiations-va/instantiations-va-applications', 'github.com/object-arts-dolphin/object-arts-dolphin-applications', 'github.com/pharo-project/pharo-utilities', 'github.com/squeak-smalltalk/squeak-utilities',
    'github.com/newspeak-language/newspeak-utilities', 'github.com/amber-smalltalk/amber-utilities', 'github.com/gnu-smalltalk/gnu-smalltalk-utilities', 'github.com/visualworks/visualworks-utilities', 'github.com/dolphin-smalltalk/dolphin-utilities',
    'github.com/va-smalltalk/va-utilities', 'github.com/gemstone/gemstone-utilities', 'github.com/cincom/cincom-utilities', 'github.com/instantiations/instantiations-utilities', 'github.com/object-arts/object-arts-utilities',
    'github.com/cincom-visualworks/cincom-visualworks-utilities', 'github.com/gemtalk/gemtalk-utilities', 'github.com/instantiations-va/instantiations-va-utilities', 'github.com/object-arts-dolphin/object-arts-dolphin-utilities'
]

m_description = [
    'обучение программированию через создание технологий с нуля', 'кураторские списки полезных ресурсов по различным темам', 'бесплатная платформа для изучения программирования и компьютерных наук', 'коллекция бесплатных публичных API для разработчиков', 'список бесплатных книг по программированию на разных языках',
    'интерактивные дорожные карты для изучения веб-разработки', 'персональный ИИ-ассистент с открытым исходным кодом', 'материалы для изучения проектирования масштабируемых систем', 'полный план изучения компьютерных наук для собеседований', 'подборка фреймворков, библиотек и инструментов для Python',
    'список бесплатного ПО для самостоятельного хостинга', 'репозиторий о проблеме переработок 996 в Китае', 'кураторская коллекция обучающих проектов на практике', 'библиотека JavaScript для создания пользовательских интерфейсов', 'исходный код ядра операционной системы Linux',
    'реализации алгоритмов и структур данных на Python', 'коллекция полезных списков, руководств и инструментов', 'фреймворк для создания пользовательских интерфейсов', 'бесплатный путь к самообразованию в области компьютерных наук', 'алгоритмы и структуры данных на JavaScript с объяснениями',
    'фреймворк машинного обучения с открытым исходным кодом от Google', 'фреймворк для управления конфигурацией оболочки zsh', 'серия книг о внутреннем устройстве языка JavaScript', 'материалы для технической подготовки к собеседованиям', 'кросс-платформенный редактор кода от Microsoft',
    'автономный ИИ-агент для автоматизации задач', 'платформа автоматизации рабочих процессов с поддержкой ИИ', '100-дневный курс изучения Python от новичка до мастера', 'фреймворк для создания кросс-платформенных мобильных приложений', 'популярный фреймворк для адаптивной веб-разработки',
    'коллекция полезных шаблонов файлов .gitignore', 'скрипты для активации Windows и Office', 'кураторский список отличных фреймворков и библиотек на Go', 'локальный запуск больших языковых моделей', 'веб-интерфейс для генерации изображений Stable Diffusion',
    'руководство по эффективному использованию командной строки', 'фреймворк для работы с трансформерами и НЛП', 'коллекция промптов для чат-ботов на базе ИИ', 'проект по предоставлению бесплатных доменных имен', 'мощный консольный загрузчик видео и аудио',
    'руководство по подготовке к собеседованиям на Java-разработчика', 'подборка интересных и начинающих проектов на GitHub', 'стандарт стиля кода для современного JavaScript', 'визуальный конструктор для создания ИИ-агентов и рабочих процессов', 'классический инструмент для загрузки видео с различных платформ',
    'фреймворк React для серверного рендеринга и fullstack', 'подготовительные материалы для собеседований по программированию', 'отображение и управление Android-устройством с ПК', 'открытый ИИ-агент для программирования в терминале', 'система оптимизации производительности для ИИ-агентов',
    'платформа для разработки рабочих процессов с ИИ-агентами', 'коллекция системных промптов и моделей ИИ-инструментов', 'фреймворк навыков для агентной разработки ПО', 'официальный репозиторий языка программирования Go', 'алгоритмы и структуры данных с подробными объяснениями',
    'платформа для инженерии ИИ-агентов и рабочих процессов', 'набор утилит для повышения продуктивности в Windows', 'дружелюбный веб-интерфейс для работы с локальными ИИ-моделями', 'короткие полезные статьи и сниппеты кода для разработчиков', 'фреймворк для создания нативных мобильных приложений на React',
    'анимированное руководство по алгоритмам и структурам данных', 'система оркестрации контейнеров для продакшена', 'фреймворк для создания кроссплатформенных десктопных приложений', 'список бесплатных облачных сервисов для разработчиков', 'виртуальная доска для рисования диаграмм от руки',
    'быстрый репозиторий с открытым исходным кодом для кодирования', 'асинхронная среда выполнения JavaScript на основе V8', 'бесплатные книги по программированию на китайском языке', 'коллекция публичных IPTV-каналов со всего мира', 'библиотека для визуализации данных с помощью SVG и Canvas',
    'популярная библиотека для создания 3D-графики в браузере', 'системный язык программирования с акцентом на безопасность', 'набор красиво оформленных доступных UI-компонентов', 'открытое приложение для удалённого рабочего стола с самохостингом', 'публичный репозиторий навыков для ИИ-агентов',
    'подборка полезных списков для хакеров и исследователей безопасности', 'библиотека для отправки HTTP-запросов на основе промисов', 'кроссплатформенный игровой движок с открытым исходным кодом', '21 урок по началу работы с генеративным ИИ', 'надмножество JavaScript со статической типизацией',
    'агентный инструмент кодирования от Anthropic для терминала', 'модульный графический интерфейс для диффузионных моделей', 'современный GUI-клиент для прокси на базе Tauri', 'китайский рейтинг популярных проектов на GitHub по языкам', 'современная среда выполнения для JavaScript и TypeScript',
    'быстрый обратный прокси для доступа к локальным серверам', 'список лучших практик разработки на Node.js', 'фреймворк для создания безопасных десктопных приложений на веб-технологиях', 'коллекция научных статей по компьютерным наукам для обсуждения', 'подборка приложений с большими языковыми моделями и ИИ-агентами',
    'инструмент для быстрой настройки современных веб-приложений на React', 'веб-скрейпинг API для сбора чистых данных для ИИ', 'новый терминал Windows с поддержкой вкладок и тем', 'открытая модель генеративного ИИ от DeepSeek', 'кураторский список качественного ПО для macOS',
    'инференс больших языковых моделей на C/C++', 'GUI-клиент для прокси-серверов на Windows с поддержкой разных ядер', 'платформа разработки на базе PostgreSQL для веб и мобильных приложений', 'ИИ-агент от Google для работы в терминале', 'платформа для создания веб-приложений с уверенностью',
    'быстрый веб-фреймворк для создания API на Python', 'высокоуровневый фреймворк для веб-разработки на Python', 'минималистичный веб-фреймворк для создания приложений на Python', 'фреймворк машинного обучения с динамическими вычислительными графами', 'библиотека машинного обучения для Python с простым интерфейсом',
    'библиотека для анализа и обработки данных на Python', 'библиотека для научных вычислений и работы с массивами', 'библиотека для создания статических и интерактивных визуализаций', 'статистическая визуализация данных на основе matplotlib', 'интерактивная библиотека для визуализации данных и дашбордов',
    'фреймворк для создания веб-приложений для машинного обучения', 'библиотека для создания веб-интерфейсов к моделям машинного обучения', 'платформа для совместного использования моделей и наборов данных ИИ', 'библиотека для доступа и обработки датасетов машинного обучения', 'быстрая библиотека токенизации для трансформеров',
    'интерактивная вычислительная среда для науки и анализа данных', 'веб-приложение для создания и совместного использования ноутбуков', 'расширяемая IDE для науки и анализа данных на базе Jupyter', 'инструмент для превращения Jupyter-ноутбуков в веб-приложения', 'интерактивные виджеты для Jupyter-ноутбуков',
    'платформа для воспроизводимых вычислений и совместной работы', 'облачная платформа для интерактивного анализа данных и ИИ', 'платформа для соревнований по машинному обучению и науке о данных', 'высокоуровневый фреймворк для глубокого обучения на Python', 'фреймворк глубокого обучения с поддержкой распределённых вычислений',
    'оптимизированная библиотека градиентного бустинга для машинного обучения', 'высокопроизводительная реализация градиентного бустинга от Microsoft', 'эффективная реализация градиентного бустинга с поддержкой категориальных признаков', 'библиотека для прогнозирования временных рядов от Facebook', 'статистическое моделирование и анализ данных на Python',
    'библиотека компьютерного зрения с открытым исходным кодом', 'библиотека для обработки изображений на Python', 'простой интерфейс для чтения и записи изображений в Python', 'научная библиотека для математики, естественных наук и инженерии', 'библиотека символьной математики на чистом Python',
    'библиотека для работы с графами и сетями в Python', 'библиотека для тематического моделирования и обработки естественного языка', 'промышленная библиотека для обработки естественного языка на Python', 'платформа для обработки естественного языка и лингвистических исследований', 'простая библиотека для анализа тональности текста',
    'трансформеры для работы с ИИ прямо в браузере на JavaScript', 'открытый формат для представления моделей машинного обучения', 'библиотека для высокопроизводительного инференса нейросетей от NVIDIA', 'набор инструментов для оптимизации инференса моделей ИИ', 'фреймворк для создания мультимодальных приложений ИИ',
    'фреймворк для исследований в области компьютерного зрения от Facebook', 'фреймворк для детекции объектов и сегментации с открытым исходным кодом', 'фреймворк для обучения и инференса моделей компьютерного зрения', 'реализация YOLOv5 для детекции объектов в реальном времени', 'современная реализация YOLOv8 для задач компьютерного зрения',
    'фундаментальная модель для сегментации изображений от Meta', 'нейросетевой модуль для контролируемой генерации изображений', 'библиотека для работы с диффузионными моделями генерации', 'библиотека для эффективной дообучения больших языковых моделей', 'библиотека для обучения с подкреплением трансформеров',
    'библиотека для ускорения обучения и инференса моделей ИИ', 'библиотека для квантования нейросетей с низкой точностью', 'оптимизированная библиотека для обучения и инференса больших моделей', 'высокопроизводительный сервер инференса для больших языковых моделей', 'оптимизированный фреймворк для инференса больших моделей',
    'унифицированный API для работы с различными провайдерами ИИ', 'фреймворк для создания приложений на базе больших языковых моделей', 'фреймворк для создания поисковых и вопросно-ответных ИИ-приложений', 'фреймворк для создания мультиагентных систем на базе ИИ', 'фреймворк для создания мультиагентных приложений с ИИ',
    'фреймворк для создания ИИ-приложений на базе .NET', 'фреймворк для создания ИИ-агентов с поддержкой памяти и инструментов', 'фреймворк для программирования с использованием языковых моделей', 'фреймворк для управляемой генерации текста с помощью ИИ', 'библиотека для структурированной генерации текста с ИИ',
    'библиотека для валидации формата вывода больших языковых моделей', 'обёртка на Python для инференса моделей llama.cpp', 'оптимизированный инференс больших языковых моделей на GPU', 'открытая платформа для самохостинга ИИ-ассистента кодирования', 'инструмент для ИИ-автодополнения кода с открытым исходным кодом',
    'платформа ИИ-автодополнения кода с поддержкой локальных моделей', 'ИИ-редактор кода с поддержкой контекста и автодополнения', 'ИИ-инструмент для программирования с интеграцией в редактор кода', 'быстрый редактор кода с поддержкой ИИ и совместной работы', 'асинхронный редактор кода с поддержкой плагинов и расширений',
    'классический текстовый редактор с мощными возможностями настройки', 'расширяемый текстовый редактор с поддержкой макросов и пакетов', 'кроссплатформенный редактор кода с поддержкой плагинов', 'редактор кода с открытым исходным кодом от сообщества', 'веб-редактор кода с поддержкой расширений и тем',
    'мощная IDE для веб-разработки от JetBrains', 'платформа для разработки на Java с поддержкой множества языков', 'профессиональная среда разработки для проектов на Python', 'кроссплатформенная IDE для .NET-разработки', 'полнофункциональная среда разработки для языков семейства Go',
    'интеллектуальная среда разработки для C и C++', 'современная IDE для разработки на языке программирования Rust', 'легковесный и быстрый редактор кода от JetBrains', 'среда разработки для Objective-C и Swift от JetBrains', 'инструмент для работы с базами данных и SQL от JetBrains',
    'профессиональная среда разработки для языка Ruby', 'мощная IDE для разработки на языке программирования PHP', 'платформа для разработки игр и мультимедийных приложений', 'единая точка входа для доступа к инструментам JetBrains', 'платформа для управления учётными записями и авторизацией',
    'платформа для совместной работы и управления проектами', 'система отслеживания проблем и управления задачами', 'сервер непрерывной интеграции и доставки для автоматизации', 'профилировщик производительности для .NET-приложений', 'инструмент анализа использования памяти для .NET-приложений',
    'расширение для Visual Studio для повышения продуктивности', 'инструмент для тестирования покрытия кода в .NET-проектах', 'декомпилятор для просмотра исходного кода .NET-сборок', 'инструмент для анализа кода и совместной работы', 'современный статически типизированный язык для JVM',
    'объектно-ориентированный язык программирования для JVM', 'динамический язык программирования для платформы Java', 'функциональный язык программирования для платформы JVM', 'язык программирования для построения масштабируемых систем', 'функциональный язык программирования для платформы Erlang VM',
    'быстрый язык программирования с синтаксисом как у Ruby', 'системный язык программирования с акцентом на производительность', 'простой, безопасный и производительный системный язык', 'простой, быстрый и безопасный язык системного программирования', 'язык системного программирования для игр и графических приложений',
    'новый язык программирования для масштабируемых систем', 'язык программирования для высокопроизводительных вычислений ИИ', 'функциональный язык для создания надёжных параллельных систем', 'язык программирования с акцентом на простоту и производительность', 'компилятор для функционального языка программирования Haskell',
    'компилятор для функционального языка PureScript', 'компилятор для функционального языка программирования Elm', 'синтаксический сахар для OCaml с акцентом на JavaScript', 'компилятор для языка программирования ReScript', 'компилятор и среда выполнения для языка программирования OCaml',
    'функциональный язык программирования для платформы .NET', 'компилятор для системного языка программирования D', 'компилятор для языка программирования высокого уровня Ada', 'компилятор для языка программирования общего назначения COBOL', 'реализация компилятора и библиотек языка программирования Fortran',
    'компилятор для процедурного языка программирования Pascal', 'среда быстрой разработки приложений для языка Object Pascal', 'компилятор для объектно-ориентированного языка программирования BASIC', 'интерпретатор для легковесного скриптового языка программирования Lua', 'интерпретатор для диалекта языка программирования Scheme',
    'расширяемый язык программирования общего назначения', 'быстрый и минималистичный интерпретатор языка JavaScript', 'интерпретатор для функционального языка программирования Scheme', 'компилятор для высокопроизводительного диалекта Common Lisp', 'интерпретатор для динамического языка программирования Lisp',
    'компактный интерпретатор для языка программирования Lisp', 'динамический язык программирования общего назначения', 'функциональный язык программирования для параллельных вычислений', 'самодокументируемая среда программирования общего назначения', 'динамический язык программирования общего назначения',
    'диалект языка программирования общего назначения', 'прототипно-ориентированный язык программирования', 'прототипно-ориентированный язык программирования общего назначения', 'объектно-ориентированный язык программирования общего назначения', 'реализация языка программирования Smalltalk с открытым исходным кодом',
    'реализация языка программирования Smalltalk с открытым исходным кодом', 'язык программирования с акцентом на простоту и безопасность', 'интерпретатор и виртуальная машина для языка программирования', 'реализация языка программирования Smalltalk с открытым исходным кодом', 'коммерческая реализация языка программирования Smalltalk',
    'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk',
    'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk', 'коммерческая реализация языка программирования Smalltalk',
    'виртуальная машина для языка программирования Pharo', 'виртуальная машина для языка программирования Squeak', 'виртуальная машина для языка программирования Newspeak', 'виртуальная машина для языка программирования Amber', 'виртуальная машина для языка программирования GNU Smalltalk',
    'виртуальная машина для языка программирования VisualWorks', 'виртуальная машина для языка программирования Dolphin', 'виртуальная машина для языка программирования VA Smalltalk', 'виртуальная машина для языка программирования GemStone', 'виртуальная машина для языка программирования Cincom',
    'виртуальная машина для языка программирования Instantiations', 'виртуальная машина для языка программирования Object Arts', 'виртуальная машина для языка программирования Cincom VisualWorks', 'виртуальная машина для языка программирования GemTalk', 'виртуальная машина для языка программирования Instantiations VA',
    'виртуальная машина для языка программирования Object Arts Dolphin', 'интегрированная среда разработки для языка программирования Pharo', 'интегрированная среда разработки для языка программирования Squeak', 'интегрированная среда разработки для языка программирования Newspeak', 'интегрированная среда разработки для языка программирования Amber',
    'интегрированная среда разработки для языка программирования GNU Smalltalk', 'интегрированная среда разработки для языка программирования VisualWorks', 'интегрированная среда разработки для языка программирования Dolphin', 'интегрированная среда разработки для языка программирования VA Smalltalk', 'интегрированная среда разработки для языка программирования GemStone',
    'интегрированная среда разработки для языка программирования Cincom', 'интегрированная среда разработки для языка программирования Instantiations', 'интегрированная среда разработки для языка программирования Object Arts', 'интегрированная среда разработки для языка программирования Cincom VisualWorks', 'интегрированная среда разработки для языка программирования GemTalk',
    'интегрированная среда разработки для языка программирования Instantiations VA', 'интегрированная среда разработки для языка программирования Object Arts Dolphin', 'набор инструментов для разработки на языке программирования Pharo', 'набор инструментов для разработки на языке программирования Squeak', 'набор инструментов для разработки на языке программирования Newspeak',
    'набор инструментов для разработки на языке программирования Amber', 'набор инструментов для разработки на языке программирования GNU Smalltalk', 'набор инструментов для разработки на языке программирования VisualWorks', 'набор инструментов для разработки на языке программирования Dolphin', 'набор инструментов для разработки на языке программирования VA Smalltalk',
    'набор инструментов для разработки на языке программирования GemStone', 'набор инструментов для разработки на языке программирования Cincom', 'набор инструментов для разработки на языке программирования Instantiations', 'набор инструментов для разработки на языке программирования Object Arts', 'набор инструментов для разработки на языке программирования Cincom VisualWorks',
    'набор инструментов для разработки на языке программирования GemTalk', 'набор инструментов для разработки на языке программирования Instantiations VA', 'набор инструментов для разработки на языке программирования Object Arts Dolphin', 'сообщество разработчиков языка программирования Pharo', 'сообщество разработчиков языка программирования Squeak',
    'сообщество разработчиков языка программирования Newspeak', 'сообщество разработчиков языка программирования Amber', 'сообщество разработчиков языка программирования GNU Smalltalk', 'сообщество разработчиков языка программирования VisualWorks', 'сообщество разработчиков языка программирования Dolphin',
    'сообщество разработчиков языка программирования VA Smalltalk', 'сообщество разработчиков языка программирования GemStone', 'сообщество разработчиков языка программирования Cincom', 'сообщество разработчиков языка программирования Instantiations', 'сообщество разработчиков языка программирования Object Arts',
    'сообщество разработчиков языка программирования Cincom VisualWorks', 'сообщество разработчиков языка программирования GemTalk', 'сообщество разработчиков языка программирования Instantiations VA', 'сообщество разработчиков языка программирования Object Arts Dolphin', 'документация для языка программирования и среды Pharo',
    'документация для языка программирования и среды Squeak', 'документация для языка программирования и среды Newspeak', 'документация для языка программирования и среды Amber', 'документация для языка программирования и среды GNU Smalltalk', 'документация для языка программирования и среды VisualWorks',
    'документация для языка программирования и среды Dolphin', 'документация для языка программирования и среды VA Smalltalk', 'документация для языка программирования и среды GemStone', 'документация для языка программирования и среды Cincom', 'документация для языка программирования и среды Instantiations',
    'документация для языка программирования и среды Object Arts', 'документация для языка программирования и среды Cincom VisualWorks', 'документация для языка программирования и среды GemTalk', 'документация для языка программирования и среды Instantiations VA', 'документация для языка программирования и среды Object Arts Dolphin',
    'практические руководства и уроки по языку программирования Pharo', 'практические руководства и уроки по языку программирования Squeak', 'практические руководства и уроки по языку программирования Newspeak', 'практические руководства и уроки по языку программирования Amber', 'практические руководства и уроки по языку программирования GNU Smalltalk',
    'практические руководства и уроки по языку программирования VisualWorks', 'практические руководства и уроки по языку программирования Dolphin', 'практические руководства и уроки по языку программирования VA Smalltalk', 'практические руководства и уроки по языку программирования GemStone', 'практические руководства и уроки по языку программирования Cincom',
    'практические руководства и уроки по языку программирования Instantiations', 'практические руководства и уроки по языку программирования Object Arts', 'практические руководства и уроки по языку программирования Cincom VisualWorks', 'практические руководства и уроки по языку программирования GemTalk', 'практические руководства и уроки по языку программирования Instantiations VA',
    'практические руководства и уроки по языку программирования Object Arts Dolphin', 'примеры кода и проекты на языке программирования Pharo', 'примеры кода и проекты на языке программирования Squeak', 'примеры кода и проекты на языке программирования Newspeak', 'примеры кода и проекты на языке программирования Amber',
    'примеры кода и проекты на языке программирования GNU Smalltalk', 'примеры кода и проекты на языке программирования VisualWorks', 'примеры кода и проекты на языке программирования Dolphin', 'примеры кода и проекты на языке программирования VA Smalltalk', 'примеры кода и проекты на языке программирования GemStone',
    'примеры кода и проекты на языке программирования Cincom', 'примеры кода и проекты на языке программирования Instantiations', 'примеры кода и проекты на языке программирования Object Arts', 'примеры кода и проекты на языке программирования Cincom VisualWorks', 'примеры кода и проекты на языке программирования GemTalk',
    'примеры кода и проекты на языке программирования Instantiations VA', 'примеры кода и проекты на языке программирования Object Arts Dolphin', 'расширения и дополнения для языка программирования и среды Pharo', 'расширения и дополнения для языка программирования и среды Squeak', 'расширения и дополнения для языка программирования и среды Newspeak',
    'расширения и дополнения для языка программирования и среды Amber', 'расширения и дополнения для языка программирования и среды GNU Smalltalk', 'расширения и дополнения для языка программирования и среды VisualWorks', 'расширения и дополнения для языка программирования и среды Dolphin', 'расширения и дополнения для языка программирования и среды VA Smalltalk',
    'расширения и дополнения для языка программирования и среды GemStone', 'расширения и дополнения для языка программирования и среды Cincom', 'расширения и дополнения для языка программирования и среды Instantiations', 'расширения и дополнения для языка программирования и среды Object Arts', 'расширения и дополнения для языка программирования и среды Cincom VisualWorks',
    'расширения и дополнения для языка программирования и среды GemTalk', 'расширения и дополнения для языка программирования и среды Instantiations VA', 'расширения и дополнения для языка программирования и среды Object Arts Dolphin', 'плагины и модули для языка программирования и среды Pharo', 'плагины и модули для языка программирования и среды Squeak',
    'плагины и модули для языка программирования и среды Newspeak', 'плагины и модули для языка программирования и среды Amber', 'плагины и модули для языка программирования и среды GNU Smalltalk', 'плагины и модули для языка программирования и среды VisualWorks', 'плагины и модули для языка программирования и среды Dolphin',
    'плагины и модули для языка программирования и среды VA Smalltalk', 'плагины и модули для языка программирования и среды GemStone', 'плагины и модули для языка программирования и среды Cincom', 'плагины и модули для языка программирования и среды Instantiations', 'плагины и модули для языка программирования и среды Object Arts',
    'плагины и модули для языка программирования и среды Cincom VisualWorks', 'плагины и модули для языка программирования и среды GemTalk', 'плагины и модули для языка программирования и среды Instantiations VA', 'плагины и модули для языка программирования и среды Object Arts Dolphin', 'пакеты и библиотеки для языка программирования и среды Pharo',
    'пакеты и библиотеки для языка программирования и среды Squeak', 'пакеты и библиотеки для языка программирования и среды Newspeak', 'пакеты и библиотеки для языка программирования и среды Amber', 'пакеты и библиотеки для языка программирования и среды GNU Smalltalk', 'пакеты и библиотеки для языка программирования и среды VisualWorks',
    'пакеты и библиотеки для языка программирования и среды Dolphin', 'пакеты и библиотеки для языка программирования и среды VA Smalltalk', 'пакеты и библиотеки для языка программирования и среды GemStone', 'пакеты и библиотеки для языка программирования и среды Cincom', 'пакеты и библиотеки для языка программирования и среды Instantiations',
    'пакеты и библиотеки для языка программирования и среды Object Arts', 'пакеты и библиотеки для языка программирования и среды Cincom VisualWorks', 'пакеты и библиотеки для языка программирования и среды GemTalk', 'пакеты и библиотеки для языка программирования и среды Instantiations VA', 'пакеты и библиотеки для языка программирования и среды Object Arts Dolphin',
    'библиотеки компонентов для языка программирования и среды Pharo', 'библиотеки компонентов для языка программирования и среды Squeak', 'библиотеки компонентов для языка программирования и среды Newspeak', 'библиотеки компонентов для языка программирования и среды Amber', 'библиотеки компонентов для языка программирования и среды GNU Smalltalk',
    'библиотеки компонентов для языка программирования и среды VisualWorks', 'библиотеки компонентов для языка программирования и среды Dolphin', 'библиотеки компонентов для языка программирования и среды VA Smalltalk', 'библиотеки компонентов для языка программирования и среды GemStone', 'библиотеки компонентов для языка программирования и среды Cincom',
    'библиотеки компонентов для языка программирования и среды Instantiations', 'библиотеки компонентов для языка программирования и среды Object Arts', 'библиотеки компонентов для языка программирования и среды Cincom VisualWorks', 'библиотеки компонентов для языка программирования и среды GemTalk', 'библиотеки компонентов для языка программирования и среды Instantiations VA',
    'библиотеки компонентов для языка программирования и среды Object Arts Dolphin', 'фреймворки для разработки приложений на языке программирования Pharo', 'фреймворки для разработки приложений на языке программирования Squeak', 'фреймворки для разработки приложений на языке программирования Newspeak', 'фреймворки для разработки приложений на языке программирования Amber',
    'фреймворки для разработки приложений на языке программирования GNU Smalltalk', 'фреймворки для разработки приложений на языке программирования VisualWorks', 'фреймворки для разработки приложений на языке программирования Dolphin', 'фреймворки для разработки приложений на языке программирования VA Smalltalk', 'фреймворки для разработки приложений на языке программирования GemStone',
    'фреймворки для разработки приложений на языке программирования Cincom', 'фреймворки для разработки приложений на языке программирования Instantiations', 'фреймворки для разработки приложений на языке программирования Object Arts', 'фреймворки для разработки приложений на языке программирования Cincom VisualWorks', 'фреймворки для разработки приложений на языке программирования GemTalk',
    'фреймворки для разработки приложений на языке программирования Instantiations VA', 'фреймворки для разработки приложений на языке программирования Object Arts Dolphin', 'готовые приложения на языке программирования и среде Pharo', 'готовые приложения на языке программирования и среде Squeak', 'готовые приложения на языке программирования и среде Newspeak',
    'готовые приложения на языке программирования и среде Amber', 'готовые приложения на языке программирования и среде GNU Smalltalk', 'готовые приложения на языке программирования и среде VisualWorks', 'готовые приложения на языке программирования и среде Dolphin', 'готовые приложения на языке программирования и среде VA Smalltalk',
    'готовые приложения на языке программирования и среде GemStone', 'готовые приложения на языке программирования и среде Cincom', 'готовые приложения на языке программирования и среде Instantiations', 'готовые приложения на языке программирования и среде Object Arts', 'готовые приложения на языке программирования и среде Cincom VisualWorks',
    'готовые приложения на языке программирования и среде GemTalk', 'готовые приложения на языке программирования и среде Instantiations VA', 'готовые приложения на языке программирования и среде Object Arts Dolphin', 'утилиты и вспомогательные инструменты для языка программирования Pharo', 'утилиты и вспомогательные инструменты для языка программирования Squeak',
    'утилиты и вспомогательные инструменты для языка программирования Newspeak', 'утилиты и вспомогательные инструменты для языка программирования Amber', 'утилиты и вспомогательные инструменты для языка программирования GNU Smalltalk', 'утилиты и вспомогательные инструменты для языка программирования VisualWorks', 'утилиты и вспомогательные инструменты для языка программирования Dolphin',
    'утилиты и вспомогательные инструменты для языка программирования VA Smalltalk', 'утилиты и вспомогательные инструменты для языка программирования GemStone', 'утилиты и вспомогательные инструменты для языка программирования Cincom', 'утилиты и вспомогательные инструменты для языка программирования Instantiations', 'утилиты и вспомогательные инструменты для языка программирования Object Arts',
    'утилиты и вспомогательные инструменты для языка программирования Cincom VisualWorks', 'утилиты и вспомогательные инструменты для языка программирования GemTalk', 'утилиты и вспомогательные инструменты для языка программирования Instantiations VA', 'утилиты и вспомогательные инструменты для языка программирования Object Arts Dolphin'
]

creators = [
    'codecrafters-io', 'sindresorhus', 'freeCodeCamp', 'public-apis', 'EbookFoundation',
    'kamranahmedse', 'OpenClaude', 'donnemartin', 'jwasham', 'vinta',
    'awesome-selfhosted', '996icu', 'practical-tutorials', 'facebook', 'torvalds',
    'TheAlgorithms', 'trimstray', 'vuejs', 'ossu', 'trekhleb',
    'tensorflow', 'ohmyzsh', 'getify', 'CyC2018', 'microsoft',
    'Significant-Gravitas', 'n8n-io', 'jackfrued', 'flutter', 'twbs',
    'github', 'massgravel', 'avelino', 'ollama', 'AUTOMATIC1111',
    'jlevy', 'huggingface', 'f', 'FreedomIntelligence', 'yt-dlp',
    'Snailclimb', '521xueweihan', 'standard', 'langflow-ai', 'ytdl-org',
    'vercel', 'yangshun', 'Genymobile', 'OpenCodeInterpreter', 'everything-ai',
    'langgenius', 'ai-collection', 'superpowers-framework', 'golang', 'labuladong',
    'langchain-ai', 'microsoft', 'open-webui', 'Chalarangelo', 'facebook',
    'krahets', 'kubernetes', 'electron', 'ripienaar', 'excalidraw',
    'ultraworkers', 'nodejs', 'jobbole', 'iptv-org', 'd3',
    'mrdoob', 'rust-lang', 'shadcn-ui', 'rustdesk', 'agentops-ai',
    'Hack-with-Github', 'axios', 'godotengine', 'microsoft', 'microsoft',
    'anthropics', 'comfyanonymous', 'clash-verge-rev', 'GrowingGit', 'denoland',
    'fatedier', 'goldbergyoni', 'tauri-apps', 'papers-we-love', 'elizabethsiegle',
    'facebook', 'firecrawl', 'microsoft', 'deepseek-ai', 'iCHAIT',
    'ggerganov', '2dust', 'supabase', 'google', 'angular',
    'tiangolo', 'django', 'pallets', 'pytorch', 'scikit-learn',
    'pandas-dev', 'numpy', 'matplotlib', 'mwaskom', 'plotly',
    'streamlit', 'gradio-app', 'huggingface', 'huggingface', 'huggingface',
    'jupyter', 'jupyter', 'jupyterlab', 'voila-dashboards', 'jupyter-widgets',
    'binder-project', 'googlecolab', 'Kaggle', 'keras-team', 'apache',
    'dmlc', 'microsoft', 'catboost', 'facebook', 'statsmodels',
    'opencv', 'python-pillow', 'imageio', 'scipy', 'sympy',
    'networkx', 'RaRe-Technologies', 'explosion', 'nltk', 'cjhutto',
    'huggingface', 'microsoft', 'NVIDIA', 'openvinotoolkit', 'google',
    'facebookresearch', 'open-mmlab', 'ultralytics', 'ultralytics', 'ultralytics',
    'facebookresearch', 'lllyasviel', 'huggingface', 'huggingface', 'huggingface',
    'huggingface', 'TimDettmers', 'unslothai', 'vllm-project', 'sgl-project',
    'BerriAI', 'run-llama', 'deepset-ai', 'crewAIInc', 'microsoft',
    'microsoft', 'phidatahq', 'stanfordnlp', 'microsoft', 'outlines-dev',
    'noamgat', 'abetlen', 'jllllll', 'TabbyML', 'continue-dev',
    'Codeium', 'getcursor', 'codeium', 'zed-industries', 'neovim',
    'vim', 'emacs-mirror', 'sublimehq', 'atom', 'adobe',
    'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains',
    'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains',
    'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains',
    'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains',
    'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains', 'JetBrains',
    'scala', 'apache', 'clojure', 'erlang', 'elixir-lang',
    'crystal-lang', 'nim-lang', 'ziglang', 'vlang', 'odin-lang',
    'carbon-language', 'modularml', 'gleam-lang', 'roc-lang', 'ghc',
    'purescript', 'elm', 'reasonml', 'rescript-lang', 'ocaml',
    'dotnet', 'dlang', 'AdaCore', 'open-cobol', 'pmodels',
    'freepascal', 'embarcadero', 'gambas3', 'lua', 'scheme',
    'racket', 'quickjs', 'gnu', 'sbcl', 'newlisp',
    'picolisp', 'janet-lang', 'fenzo-lang', 'factor', 'red',
    'Rebol', 'io-language', 'self-language', 'smalltalk', 'pharo-project',
    'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk', 'visualworks',
    'dolphin-smalltalk', 'va-smalltalk', 'gemstone', 'cincom', 'instantiations',
    'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va', 'object-arts-dolphin',
    'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk',
    'visualworks', 'dolphin-smalltalk', 'va-smalltalk', 'gemstone', 'cincom',
    'instantiations', 'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va',
    'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk',
    'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk', 'va-smalltalk', 'gemstone',
    'cincom', 'instantiations', 'object-arts', 'cincom-visualworks', 'gemtalk',
    'instantiations-va', 'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk', 'newspeak-language',
    'amber-smalltalk', 'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk', 'va-smalltalk',
    'gemstone', 'cincom', 'instantiations', 'object-arts', 'cincom-visualworks',
    'gemtalk', 'instantiations-va', 'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk',
    'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk',
    'va-smalltalk', 'gemstone', 'cincom', 'instantiations', 'object-arts',
    'cincom-visualworks', 'gemtalk', 'instantiations-va', 'object-arts-dolphin', 'pharo-project',
    'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk', 'visualworks',
    'dolphin-smalltalk', 'va-smalltalk', 'gemstone', 'cincom', 'instantiations',
    'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va', 'object-arts-dolphin',
    'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk',
    'visualworks', 'dolphin-smalltalk', 'va-smalltalk', 'gemstone', 'cincom',
    'instantiations', 'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va',
    'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk',
    'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk', 'va-smalltalk', 'gemstone',
    'cincom', 'instantiations', 'object-arts', 'cincom-visualworks', 'gemtalk',
    'instantiations-va', 'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk', 'newspeak-language',
    'amber-smalltalk', 'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk', 'va-smalltalk',
    'gemstone', 'cincom', 'instantiations', 'object-arts', 'cincom-visualworks',
    'gemtalk', 'instantiations-va', 'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk',
    'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk',
    'va-smalltalk', 'gemstone', 'cincom', 'instantiations', 'object-arts',
    'cincom-visualworks', 'gemtalk', 'instantiations-va', 'object-arts-dolphin', 'pharo-project',
    'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk', 'visualworks',
    'dolphin-smalltalk', 'va-smalltalk', 'gemstone', 'cincom', 'instantiations',
    'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va', 'object-arts-dolphin',
    'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk', 'gnu-smalltalk',
    'visualworks', 'dolphin-smalltalk', 'va-smalltalk', 'gemstone', 'cincom',
    'instantiations', 'object-arts', 'cincom-visualworks', 'gemtalk', 'instantiations-va',
    'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk', 'newspeak-language', 'amber-smalltalk',
    'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk', 'va-smalltalk', 'gemstone',
    'cincom', 'instantiations', 'object-arts', 'cincom-visualworks', 'gemtalk',
    'instantiations-va', 'object-arts-dolphin', 'pharo-project', 'squeak-smalltalk', 'newspeak-language',
    'amber-smalltalk', 'gnu-smalltalk', 'visualworks', 'dolphin-smalltalk', 'va-smalltalk',
    'gemstone', 'cincom', 'instantiations', 'object-arts', 'cincom-visualworks',
    'gemtalk', 'instantiations-va', 'object-arts-dolphin'
]

main_lang = [
    'Markdown', 'None', 'TypeScript', 'Python', 'Python',
    'TypeScript', 'TypeScript', 'Python', 'None', 'Python',
    'None', 'None', 'None', 'JavaScript', 'C',
    'Python', 'None', 'TypeScript', 'HTML', 'JavaScript',
    'C++', 'Shell', 'None', 'None', 'TypeScript',
    'Python', 'TypeScript', 'Jupyter Notebook', 'Dart', 'MDX',
    'None', 'Batchfile', 'Go', 'Go', 'Python',
    'None', 'Python', 'HTML', 'HTML', 'Python',
    'Java', 'Python', 'JavaScript', 'Python', 'Python',
    'JavaScript', 'TypeScript', 'C', 'TypeScript', 'JavaScript',
    'TypeScript', 'None', 'Shell', 'Go', 'Markdown',
    'Python', 'C#', 'Python', 'JavaScript', 'C++',
    'Java', 'Go', 'TypeScript', 'HTML', 'TypeScript',
    'Rust', 'JavaScript', 'None', 'TypeScript', 'Shell',
    'C', 'JavaScript', 'Rust', 'TypeScript', 'Rust',
    'Python', 'JavaScript', 'C++', 'Jupyter Notebook', 'TypeScript',
    'Shell', 'TypeScript', 'Python', 'JavaScript', 'TypeScript',
    'JavaScript', 'TypeScript', 'C++', 'Python', 'TypeScript',
    'TypeScript', 'TypeScript', 'TypeScript', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'None', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'JavaScript', 'C++', 'C++', 'C++', 'C++',
    'Python', 'C++', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python']