categories_list = [
    'Обучение и самообразование',
    'Сообщества и списки',
    'Искусственный интеллект и ML',
    'Веб-разработка',
    'Операционные системы',
    'Чистый код и алгоритмы',
    'Инструменты разработчика',
    'Автоматизация и скриптинг',
    'Мобильная и десктопная разработка',
    'Безопасность и конфиденциальность',
    'Языки программирования',
    'DevOps и инфраструктура',
    'Игры и развлечения',
    'Научные вычисления и графика',
    'Базы данных и аналитика',
    'Специфичные платформы'
]

category_score = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

names = [
    'build-your-own-x', 'awesome', 'freeCodeCamp', 'public-apis', 'free-programming-books',
    'developer-roadmap', 'system-design-primer', 'coding-interview-university', 'awesome-python', 'awesome-selfhosted',
    'project-based-learning', 'react', 'linux', 'Python', 'the-book-of-secret-knowledge',
    'vue', 'computer-science', 'javascript-algorithms', 'tensorflow', 'ohmyzsh',
    'You-Dont-Know-JS', 'vscode', 'AutoGPT', 'n8n', 'Python-100-Days',
    'flutter', 'bootstrap', 'gitignore', 'Microsoft-Activation-Scripts', 'awesome-go',
    'ollama', 'stable-diffusion-webui', 'the-art-of-command-line', 'transformers', 'yt-dlp',
    'JavaGuide', 'HelloGitHub', 'next.js', 'tech-interview-handbook', 'scrcpy',
    'dify', 'go', 'langchain', 'PowerToys', 'open-webui',
    '30-seconds-of-code', 'react-native', 'hello-algo', 'kubernetes', 'electron',
    'free-for-dev', 'excalidraw', 'node', 'd3', 'three.js',
    'rust', 'rustdesk', 'Awesome-Hacking', 'axios', 'godot',
    'generative-ai-for-beginners', 'TypeScript', 'ComfyUI', 'deno', 'frp',
    'tauri', 'create-react-app', 'terminal', 'llama.cpp', 'supabase',
    'angular', 'fastapi', 'django', 'flask', 'pytorch',
    'scikit-learn', 'pandas', 'numpy', 'matplotlib', 'seaborn',
    'plotly', 'streamlit', 'gradio', 'huggingface', 'jupyter',
    'opencv', 'scipy', 'keras', 'xgboost', 'pytorch3d',
    'spacy', 'nltk', 'onnx', 'tensorrt', 'openvino',
    'detectron2', 'ultralytics', 'diffusers', 'vllm', 'crewai'
]

category = [
    'Обучение и самообразование', 'Сообщества и списки', 'Обучение и самообразование', 'Сообщества и списки', 'Сообщества и списки',
    'Обучение и самообразование', 'Обучение и самообразование', 'Обучение и самообразование', 'Сообщества и списки', 'Сообщества и списки',
    'Обучение и самообразование', 'Веб-разработка', 'Операционные системы', 'Чистый код и алгоритмы', 'Сообщества и списки',
    'Веб-разработка', 'Обучение и самообразование', 'Чистый код и алгоритмы', 'Искусственный интеллект и ML', 'Операционные системы',
    'Обучение и самообразование', 'Инструменты разработчика', 'Искусственный интеллект и ML', 'Автоматизация и скриптинг', 'Обучение и самообразование',
    'Мобильная и десктопная разработка', 'Веб-разработка', 'Инструменты разработчика', 'Безопасность и конфиденциальность', 'Сообщества и списки',
    'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Операционные системы', 'Искусственный интеллект и ML', 'Автоматизация и скриптинг',
    'Обучение и самообразование', 'Сообщества и списки', 'Веб-разработка', 'Обучение и самообразование', 'Мобильная и десктопная разработка',
    'Искусственный интеллект и ML', 'Языки программирования', 'Искусственный интеллект и ML', 'Инструменты разработчика', 'Искусственный интеллект и ML',
    'Чистый код и алгоритмы', 'Мобильная и десктопная разработка', 'Обучение и самообразование', 'DevOps и инфраструктура', 'Мобильная и десктопная разработка',
    'Сообщества и списки', 'Инструменты разработчика', 'Языки программирования', 'Веб-разработка', 'Научные вычисления и графика',
    'Языки программирования', 'Мобильная и десктопная разработка', 'Безопасность и конфиденциальность', 'Веб-разработка', 'Игры и развлечения',
    'Обучение и самообразование', 'Языки программирования', 'Искусственный интеллект и ML', 'Языки программирования', 'DevOps и инфраструктура',
    'Мобильная и десктопная разработка', 'Веб-разработка', 'Инструменты разработчика', 'Искусственный интеллект и ML', 'Базы данных и аналитика',
    'Веб-разработка', 'Веб-разработка', 'Веб-разработка', 'Веб-разработка', 'Искусственный интеллект и ML',
    'Искусственный интеллект и ML', 'Базы данных и аналитика', 'Научные вычисления и графика', 'Научные вычисления и графика', 'Базы данных и аналитика',
    'Базы данных и аналитика', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Специфичные платформы',
    'Научные вычисления и графика', 'Научные вычисления и графика', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML',
    'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML',
    'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML', 'Искусственный интеллект и ML'
]

link = [
    'github.com/codecrafters-io/build-your-own-x', 'github.com/sindresorhus/awesome', 'github.com/freeCodeCamp/freeCodeCamp', 'github.com/public-apis/public-apis', 'github.com/EbookFoundation/free-programming-books',
    'github.com/kamranahmedse/developer-roadmap', 'github.com/donnemartin/system-design-primer', 'github.com/jwasham/coding-interview-university', 'github.com/vinta/awesome-python', 'github.com/awesome-selfhosted/awesome-selfhosted',
    'github.com/practical-tutorials/project-based-learning', 'github.com/facebook/react', 'github.com/torvalds/linux', 'github.com/TheAlgorithms/Python', 'github.com/trimstray/the-book-of-secret-knowledge',
    'github.com/vuejs/vue', 'github.com/ossu/computer-science', 'github.com/trekhleb/javascript-algorithms', 'github.com/tensorflow/tensorflow', 'github.com/ohmyzsh/ohmyzsh',
    'github.com/getify/You-Dont-Know-JS', 'github.com/microsoft/vscode', 'github.com/Significant-Gravitas/AutoGPT', 'github.com/n8n-io/n8n', 'github.com/jackfrued/Python-100-Days',
    'github.com/flutter/flutter', 'github.com/twbs/bootstrap', 'github.com/github/gitignore', 'github.com/massgravel/Microsoft-Activation-Scripts', 'github.com/avelino/awesome-go',
    'github.com/ollama/ollama', 'github.com/AUTOMATIC1111/stable-diffusion-webui', 'github.com/jlevy/the-art-of-command-line', 'github.com/huggingface/transformers', 'github.com/yt-dlp/yt-dlp',
    'github.com/Snailclimb/JavaGuide', 'github.com/521xueweihan/HelloGitHub', 'github.com/vercel/next.js', 'github.com/yangshun/tech-interview-handbook', 'github.com/Genymobile/scrcpy',
    'github.com/langgenius/dify', 'github.com/golang/go', 'github.com/langchain-ai/langchain', 'github.com/microsoft/PowerToys', 'github.com/open-webui/open-webui',
    'github.com/Chalarangelo/30-seconds-of-code', 'github.com/facebook/react-native', 'github.com/krahets/hello-algo', 'github.com/kubernetes/kubernetes', 'github.com/electron/electron',
    'github.com/ripienaar/free-for-dev', 'github.com/excalidraw/excalidraw', 'github.com/nodejs/node', 'github.com/d3/d3', 'github.com/mrdoob/three.js',
    'github.com/rust-lang/rust', 'github.com/rustdesk/rustdesk', 'github.com/Hack-with-Github/Awesome-Hacking', 'github.com/axios/axios', 'github.com/godotengine/godot',
    'github.com/microsoft/generative-ai-for-beginners', 'github.com/microsoft/TypeScript', 'github.com/comfyanonymous/ComfyUI', 'github.com/denoland/deno', 'github.com/fatedier/frp',
    'github.com/tauri-apps/tauri', 'github.com/facebook/create-react-app', 'github.com/microsoft/terminal', 'github.com/ggerganov/llama.cpp', 'github.com/supabase/supabase',
    'github.com/angular/angular', 'github.com/tiangolo/fastapi', 'github.com/django/django', 'github.com/pallets/flask', 'github.com/pytorch/pytorch',
    'github.com/scikit-learn/scikit-learn', 'github.com/pandas-dev/pandas', 'github.com/numpy/numpy', 'github.com/matplotlib/matplotlib', 'github.com/mwaskom/seaborn',
    'github.com/plotly/plotly', 'github.com/streamlit/streamlit', 'github.com/gradio-app/gradio', 'github.com/huggingface', 'github.com/jupyter/jupyter',
    'github.com/opencv/opencv', 'github.com/scipy/scipy', 'github.com/keras-team/keras', 'github.com/dmlc/xgboost', 'github.com/facebookresearch/pytorch3d',
    'github.com/explosion/spaCy', 'github.com/nltk/nltk', 'github.com/microsoft/onnx', 'github.com/NVIDIA/TensorRT', 'github.com/openvinotoolkit/openvino',
    'github.com/facebookresearch/detectron2', 'github.com/ultralytics/ultralytics', 'github.com/huggingface/diffusers', 'github.com/vllm-project/vllm', 'github.com/crewAIInc/crewAI'
]

m_description = [
    'создание технологий с нуля для обучения', 'кураторские списки ресурсов по всем темам', 'бесплатное обучение программированию', 'коллекция бесплатных API', 'список бесплатных книг по программированию',
    'дорожные карты для веб-разработки', 'проектирование масштабируемых систем', 'полный план подготовки к собеседованиям', 'лучшие Python-библиотеки и фреймворки', 'список ПО для самостоятельного хостинга',
    'обучение через практические проекты', 'библиотека для UI на JavaScript', 'ядро операционной системы Linux', 'алгоритмы на Python', 'коллекция полезных списков и руководств',
    'фреймворк для UI на JavaScript', 'бесплатный курс Computer Science', 'алгоритмы на JavaScript', 'фреймворк машинного обучения от Google', 'управление конфигурацией zsh',
    'серия книг по JavaScript', 'редактор кода от Microsoft', 'автономный ИИ-агент', 'автоматизация рабочих процессов с ИИ', '100-дневный курс Python',
    'кроссплатформенная мобильная разработка', 'адаптивный веб-фреймворк', 'шаблоны .gitignore', 'активация Windows и Office', 'лучшие Go-библиотеки',
    'локальный запуск LLM', 'генерация изображений через веб-интерфейс', 'эффективное использование командной строки', 'трансформеры для НЛП', 'загрузчик видео и аудио',
    'подготовка к собеседованию Java', 'интересные GitHub-проекты', 'React-фреймворк для fullstack', 'материалы для техсобеседований', 'управление Android с ПК',
    'платформа для ИИ-агентов', 'язык программирования Go', 'фреймворк для LLM-приложений', 'утилиты для продуктивности Windows', 'веб-интерфейс для LLM',
    'короткие сниппеты кода', 'нативные мобильные приложения на React', 'анимированные алгоритмы', 'оркестрация контейнеров', 'десктопные приложения на веб-технологиях',
    'бесплатные облачные сервисы', 'виртуальная доска для диаграмм', 'среда выполнения JavaScript', 'визуализация данных', '3D-графика в браузере',
    'системный язык программирования', 'удалённый рабочий стол с самохостингом', 'ресурсы для хакеров', 'HTTP-запросы на промисах', 'игровой движок с открытым кодом',
    'уроки по генеративному ИИ', 'статическая типизация для JS', 'графический интерфейс для диффузионных моделей', 'среда выполнения JS/TS', 'быстрый обратный прокси',
    'безопасные десктопные приложения', 'быстрая настройка React-приложений', 'терминал Windows с вкладками', 'инференс LLM на C/C++', 'платформа на базе PostgreSQL',
    'фреймворк для веб-приложений', 'быстрый веб-фреймворк для API', 'высокоуровневый веб-фреймворк', 'минималистичный веб-фреймворк', 'динамические выч. графы для ML',
    'библиотека ML на Python', 'анализ и обработка данных', 'научные вычисления', 'статическая визуализация', 'статистическая визуализация',
    'интерактивные дашборды', 'веб-приложения для ML', 'интерфейсы для ML-моделей', 'платформа для моделей и датасетов', 'интерактивная среда для науки',
    'компьютерное зрение', 'научные вычисления', 'высокоуровневый фреймворк для глубокого обучения', 'градиентный бустинг', '3D-глубокое обучение',
    'обработка естественного языка', 'НЛП-библиотека', 'открытый формат моделей ML', 'высокопроизводительный инференс', 'оптимизация инференса',
    'детекция объектов и сегментация', 'модели компьютерного зрения', 'диффузионные модели', 'высокопроизводительный сервер LLM', 'мультиагентные ИИ-системы'
]

creators = [
    'codecrafters-io', 'sindresorhus', 'freeCodeCamp', 'public-apis', 'EbookFoundation',
    'kamranahmedse', 'donnemartin', 'jwasham', 'vinta', 'awesome-selfhosted',
    'practical-tutorials', 'facebook', 'torvalds', 'TheAlgorithms', 'trimstray',
    'vuejs', 'ossu', 'trekhleb', 'tensorflow', 'ohmyzsh',
    'getify', 'microsoft', 'Significant-Gravitas', 'n8n-io', 'jackfrued',
    'flutter', 'twbs', 'github', 'massgravel', 'avelino',
    'ollama', 'AUTOMATIC1111', 'jlevy', 'huggingface', 'yt-dlp',
    'Snailclimb', '521xueweihan', 'vercel', 'yangshun', 'Genymobile',
    'langgenius', 'golang', 'langchain-ai', 'microsoft', 'open-webui',
    'Chalarangelo', 'facebook', 'krahets', 'kubernetes', 'electron',
    'ripienaar', 'excalidraw', 'nodejs', 'd3', 'mrdoob',
    'rust-lang', 'rustdesk', 'Hack-with-Github', 'axios', 'godotengine',
    'microsoft', 'microsoft', 'comfyanonymous', 'denoland', 'fatedier',
    'tauri-apps', 'facebook', 'microsoft', 'ggerganov', 'supabase',
    'angular', 'tiangolo', 'django', 'pallets', 'pytorch',
    'scikit-learn', 'pandas-dev', 'numpy', 'matplotlib', 'mwaskom',
    'plotly', 'streamlit', 'gradio-app', 'huggingface', 'jupyter',
    'opencv', 'scipy', 'keras-team', 'dmlc', 'facebookresearch',
    'explosion', 'nltk', 'microsoft', 'NVIDIA', 'openvinotoolkit',
    'facebookresearch', 'ultralytics', 'huggingface', 'vllm-project', 'crewAIInc'
]

main_lang = [
    'Markdown', 'None', 'TypeScript', 'Python', 'Python',
    'TypeScript', 'Python', 'None', 'Python', 'None',
    'None', 'JavaScript', 'C', 'Python', 'None',
    'TypeScript', 'HTML', 'JavaScript', 'C++', 'Shell',
    'None', 'TypeScript', 'Python', 'TypeScript', 'Jupyter Notebook',
    'Dart', 'MDX', 'None', 'Batchfile', 'Go',
    'Go', 'Python', 'None', 'Python', 'Python',
    'Java', 'Python', 'JavaScript', 'TypeScript', 'C',
    'TypeScript', 'Go', 'Python', 'C#', 'Python',
    'JavaScript', 'C++', 'Java', 'Go', 'TypeScript',
    'HTML', 'TypeScript', 'Rust', 'JavaScript', 'C',
    'Rust', 'TypeScript', 'Python', 'JavaScript', 'C++',
    'Jupyter Notebook', 'TypeScript', 'TypeScript', 'TypeScript', 'JavaScript',
    'TypeScript', 'TypeScript', 'C++', 'Python', 'TypeScript',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'Python', 'Python',
    'Python', 'Python', 'Python', 'None', 'Python',
    'C++', 'Python', 'Python', 'C++', 'Python',
    'Python', 'Python', 'C++', 'C++', 'C++',
    'Python', 'Python', 'Python', 'Python', 'Python'
]